<a href="https://colab.research.google.com/github/XU2024/Assignment4/blob/main/(Check%20the%20final%20one)Final%20version%20of%20Assignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#[PyMan 0.9.31 Introduction to Python for Science](https://physics.nyu.edu/pine/pymanual/html/pymanMaster.html)

###The following exercises correspond to chapter [4: Input and Output](https://physics.nyu.edu/pine/pymanual/html/chap4/chap4_io.html)

In [1]:
import numpy as np

Look left <-----

There's a folder icon on the bar. 

Click it. 

You should see a folder called "sample_data." You don't need this sample data! It's a gift from google that you don't want. I wish there was some kind of [metaphor](https://www.dailymotion.com/video/x2hwqlw) for this situation.

The code block below will download the data file and display its contents. 

In [2]:
!wget -nc https://raw.githubusercontent.com/NYUExperimentalPhysics1-2021/Assignment4/main/assignment4data.txt
!more assignment4data.txt

--2021-10-08 19:56:01--  https://raw.githubusercontent.com/NYUExperimentalPhysics1-2021/Assignment4/main/assignment4data.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 582 [text/plain]
Saving to: ‘assignment4data.txt’

assignment4data.txt 100%[===================>]     582  --.-KB/s    in 0s      

2021-10-08 19:56:01 (30.0 MB/s) - ‘assignment4data.txt’ saved [582/582]

Date: 2013-09-16
Data taken by Liam and Selena
frequency (Hz) amplitude (mm)  amp error (mm)
  0.7500        13.52         0.32
  1.7885        12.11         0.92
  2.8269        14.27         0.73
  3.8654        16.60         2.06
  4.9038        22.91         1.75
  5.9423        35.28         0.91
  6.9808        60.99         0.99
  8.0192        33.38         0.36
  9.0577        1

You should check to see if your file is there. Click the folder with the circle arrow above the file lists (below the world Files); if you hover, it will say "Refresh." Once it refreshes, you should see the file assignment4data.txt in the directory below the sample_data folder.


##4.5.1

Write a Python program that calculates how much money you can spend each day for lunch for the rest of the month based on today's date and how much money you currently have in your lunch account. The program should ask you: (1) how much money you have in your account, (2) what today's date is, and (3) how many days there are in this month. The program should return your daily allowance. The results of running your program should look like this:

```
How much money (in dollars) in your lunch account? 118.39

What day of the month is today? 17

How many days in this month? 30

You can spend $8.46 each day for the rest of the month.
```

_Extra:_ Create a dictionary (see _[Dictionaries](https://physics.nyu.edu/pine/pymanual/html/chap3/chap3_arrays.html#chap3dictionaries)_) that stores the number of days in each month (forget about leap years) and have your program ask what month it is rather than the number of days in the month.

In [3]:
##USE THIS CODE BLOCK TO COMPLETE EXERCISE 4.5.1##

Numberdays = {"Jan":31,"Feb":28,"Mar":31, "Apr":30, "May":31, "Jun":30, "July":31, "Aug":31, "Sep":30, "Oct":31, "Nov":30, "Dec":31}
Numberdays ["Sep"]

Money = input("How much money (in dollars) in your lunch account?:")
Money = float(Money)
Today =input("What day of the month is today?:")
Monthdays = input("How many days in this month?:")


Restdays = int(Monthdays) - int(Today) +1 
MoneyEachDay = Money/Restdays

print('You can spend $', MoneyEachDay, 'each day for the rest of the month')



How much money (in dollars) in your lunch account?:118.39
What day of the month is today?:17
How many days in this month?:30
You can spend $ 8.456428571428571 each day for the rest of the month


##4.5.2

From the IPython terminal, create the following three NumPy arrays:

```
a = array([1, 3, 5, 7])
b = array([8, 7, 5, 4])
c = array([0, 9,-6,-8])
```

Now use the `zip` function to create the object `d` defined as

```
d = zip(a, b, c)
```

Print `d` out at the terminal prompt. What kind of object is `d`? Hint: It is not a NumPy array. Convert `d` into a NumPy array and call that array `e`. Type `e` at the terminal prompt so that `e` is printed out on the IPython terminal. One of the elements of `e` is `-8`. Show how to address and print out just that element of `e`. Show how to address that same element of `d`. What has become of the three original arrays `a`,`b`, and `c`, that is, how do they appear in `e`?

In [4]:
##USE THIS CODE BLOCK TO COMPLETE EXERCISE 4.5.2##
import numpy as np


a=np.array([1,3,5,7])
print (a)

b=np.array([8,7,5,4])
print (b)

c=np.array([0,9,-6,-8])
print (c)

d= zip(a, b, c)
print (d)

e= np.array(list(d))
print(e)

print(e[3][2])

[1 3 5 7]
[8 7 5 4]
[ 0  9 -6 -8]
[[ 1  8  0]
 [ 3  7  9]
 [ 5  5 -6]
 [ 7  4 -8]]
-8


##4.5.3

Write a Python script to read "assignment4data.txt" into three NumPy arrays with the variable names `f`,`a`,`da` for the frequency, amplitude, and amplitude error.

```
Date: 2013-09-16
Data taken by Liam and Selena
frequency (Hz) amplitude (mm)  amp error (mm)
  0.7500        13.52         0.32
  1.7885        12.11         0.92
  2.8269        14.27         0.73
  3.8654        16.60         2.06
  4.9038        22.91         1.75
  5.9423        35.28         0.91
  6.9808        60.99         0.99
  8.0192        33.38         0.36
  9.0577        17.78         2.32
 10.0962        10.99         0.21
 11.1346         7.47         0.48
 12.1731         6.72         0.51
 13.2115         4.40         0.58
 14.2500         4.07         0.63
 ```

Show that you have correctly read in the data by having your script print out to your computer screen the three arrays. Format the printing so that it produces output like this:

```
f =
[  0.75     1.7885   2.8269   3.8654   4.9038   5.9423
   6.9808   8.0192   9.0577  10.0962  11.1346  12.1731
   13.2115  14.25  ]
a =
[ 13.52  12.11  14.27  16.6   22.91  35.28  60.99  33.38
  17.78  10.99   7.47   6.72   4.4    4.07]
da =
[ 0.32  0.92  0.73  2.06  1.75  0.91  0.99  0.36  2.32
  0.21  0.48  0.51  0.58  0.63]
```

Note that the array `f` is displayed with four digits to the right of the decimal point while the arrays `a` and `da` are displayed with only two. The columns of the displayed arrays need not line up as they do above.

In [6]:
import numpy as np
f,a,da = np.loadtxt("assignment4data.txt", skiprows=3, unpack=True)
print ("f=",f)
print ("a=",a)
print ("da=",da) 

f= [ 0.75    1.7885  2.8269  3.8654  4.9038  5.9423  6.9808  8.0192  9.0577
 10.0962 11.1346 12.1731 13.2115 14.25  ]
a= [13.52 12.11 14.27 16.6  22.91 35.28 60.99 33.38 17.78 10.99  7.47  6.72
  4.4   4.07]
da= [0.32 0.92 0.73 2.06 1.75 0.91 0.99 0.36 2.32 0.21 0.48 0.51 0.58 0.63]


##4.5.4

Now write the data you just read (`f`, `a`, `da`)  to a data file, including the header, with the data displayed in three columns, just as its displayed in the problem above. It's ok if the header lines begin with the `#` comment character. Your data file should be called `textfileanswer.txt`. 

In [16]:
##USE THIS CODE BLOCK TO COMPLETE EXERCISE 4.5.4##
import numpy as np

f,a,da = np.loadtxt("assignment4data.txt", skiprows=3, unpack=True)

g=np.array(list(zip(f,a,da)))


info='n\n frequency(hz) amplitute(mm) amerror(mm)'
np.savetxt('textfileanswer.txt', g, fmt="%0.18e",delimiter="", newline="\n", header="Data taken by Liam and Selena"+info, comments="# ")

d=open("textfileanswer.txt","r")
print(d.read())

# Data taken by Liam and Selenan
#  frequency(hz) amplitute(mm) amerror(mm)
7.500000000000000000e-011.351999999999999957e+013.200000000000000067e-01
1.788499999999999979e+001.210999999999999943e+019.200000000000000400e-01
2.826900000000000190e+001.426999999999999957e+017.299999999999999822e-01
3.865400000000000169e+001.660000000000000142e+012.060000000000000053e+00
4.903800000000000381e+002.291000000000000014e+011.750000000000000000e+00
5.942300000000000360e+003.528000000000000114e+019.100000000000000311e-01
6.980800000000000338e+006.099000000000000199e+019.899999999999999911e-01
8.019199999999999662e+003.338000000000000256e+013.599999999999999867e-01
9.057700000000000529e+001.778000000000000114e+012.319999999999999840e+00
1.009619999999999962e+011.099000000000000021e+012.099999999999999922e-01
1.113460000000000072e+017.469999999999999751e+004.799999999999999822e-01
1.217309999999999981e+016.719999999999999751e+005.100000000000000089e-01
1.321149999999999913e+014.400000000000000355e+00

##4.5.5

Now write the same data to a csv data file, **without the header**, to a data file called `csvfileanswer.csv` with the data displayed in three columns. Use a single format specifier and set it to `"%0.16e"`. If you have access to a spreadsheet program (like MS Excel), try opening the file you have created with your Python script and verify that the arrays are displayed in three columns. Note that your csv file should have the extension `.csv`.

In [26]:
##USE THIS CODE BLOCK TO COMPLETE EXERCISE 4.5.5##
import numpy as np

!wget -nc https://raw.githubusercontent.com/NYUExpertimentPhysics1-2021/Assignment4/main/assignment4data.txt
!more assignment4data.txt

f,a,da=np.loadtxt("assignment4data.txt", skiprows=3, unpack=True)

g=np.array(list(zip(f,a,da)))
np.savetxt('csvfileanswer.csv',g, fmt="%0.16e", delimiter=" ", newline="\n", comments="# ")

d=open("csvfileanswer.csv","r")
print(d.read())

File ‘assignment4data.txt’ already there; not retrieving.

Date: 2013-09-16
Data taken by Liam and Selena
frequency (Hz) amplitude (mm)  amp error (mm)
  0.7500        13.52         0.32
  1.7885        12.11         0.92
  2.8269        14.27         0.73
  3.8654        16.60         2.06
  4.9038        22.91         1.75
  5.9423        35.28         0.91
  6.9808        60.99         0.99
  8.0192        33.38         0.36
  9.0577        17.78         2.32
 10.0962        10.99         0.21
 11.1346         7.47         0.48
 12.1731         6.72         0.51
 13.2115         4.40         0.58
 14.2500         4.07         0.63
7.5000000000000000e-01 1.3520000000000000e+01 3.2000000000000001e-01
1.7885000000000000e+00 1.2109999999999999e+01 9.2000000000000004e-01
2.8269000000000002e+00 1.4270000000000000e+01 7.2999999999999998e-01
3.8654000000000002e+00 1.6600000000000001e+01 2.0600000000000001e+00
4.9038000000000004e+00 2.2910000000000000e+01 1.7500000000000000e+00
5.94230000000

#YOU'RE NOT DONE!

First, you should save a copy of this notebook to your github repository, using File>Save a copy in github, as usual. But this only commits your notebook. You'll also need to save the data files you created too!

As soon as you close this browser, your beautiful files `textanswer.txt` and `csvanswer.csv` will dissappear into the ether. You need to turn them in so you can get a grade! 

1. Click on the dots next to each file's name (or right click on the file name) and select download. 

2. Open your repository on github ( it will be located at
https://github.com/NYUExperimentalPhysics1-2021/assignment4-yourgithubusername  - you can also get to the repository from the github page that opens when you save your notebook in github) and click on the "add file" button and select upload. **OR**  you can go straight to the upload page at
https://github.com/NYUExperimentalPhysics1-2021/assignment4-yourgithubusername/upload/main
You'll have to replace "yourgithubusername" with your github username

3. Drag the files you downloaded in Step 1 onto the upload box. 

4. Click commit changes (you can edit the commit message first if you want)


